### ISSUE TITLE
Problem importing `List::Util`

### ISSUE THREAD

**Issue by robscovell-ts** [mschout/perl-log-dispatch-filerotate#26]
I have experienced this on two systems now when trying to migrate 'legacy' perl code.

I am using Perl 5.16.

This is the error I get when I invoke code that uses `Log::Dispatch::FileRotate`

```
ERROR: can't load appenderclass 'Log::Dispatch::FileRotate'
"all" is not exported by the List::Util module
Can't continue after import errors at /usr/local/share/perl5/Specio/OO.pm line 7.\n
```

**Comment by mschout** [comment]
This really has nothing to do with `Log::Dispatch::FileRotate`. 

The `List::Util` dependency is in `Specio::OO`, which `Log::Dispatch` depends on.  TL;DR your `List::Util` is too old due to an outdated dependency 3 times removed from `Log::Dispatch::FileRotate`, and was fixed 2 levels away sometime long ago :)

I suppose the real fix here is to just set minimum requirement for `Log::Dispatch` to v2.59 where, from a quick skim of `Makefile.PL` changes it seems the minumum Specio version requirement is set to 0.32.

**Comment by robscovell-ts** [comment]
> This really has nothing to do with `Log::Dispatch::FileRotate`.
> 
> The `List::Util` dependency is in `Specio::OO`, which `Log::Dispatch` depends on. TL;DR your `List::Util` is too old due to an outdated dependency 3 times removed from `Log::Dispatch::FileRotate`, and was fixed 2 levels away sometime long ago :)
> 
> I suppose the real fix here is to just set minimum requirement for `Log::Dispatch` to v2.59 where, from a quick skim of `Makefile.PL` changes it seems the minumum Specio version requirement is set to 0.32.

Thank you for this information and advice. It's always hard to know at what point in the dependency tree to raise an issue!
